dist: xenial
language: python
python:
  - "3.8"
before_install:
  - python -m pip install --upgrade pip
install:
  - pip install -r requirements.txt
script:
- pytest -s --cov=kwx tests
after_success:
- bash <(curl -s https://codecov.io/bash)
