dist: xenial
language: python
python:
  - "3.8"
before_install:
  - "pip install -U pip"
  - "python setup.py install"
script:
- pytest -s --cov=kwx tests
after_success:
- bash <(curl -s https://codecov.io/bash)
